import Vue from 'vue'
// Vue.prototype.$imageUrl = 'https://api.runyourlife.checkmy.dev/images/'
// Vue.prototype.$imageUrl2 = 'https://api.runyourlife.checkmy.dev/'
Vue.prototype.$imageUrl = process.env.basePath
Vue.prototype.$imageUrl2 = 'http://localhost:9292/'
Vue.prototype.$countries = 'countries'
Vue.prototype.$cities = 'cities'
Vue.prototype.$zipcodes = 'zipcodes'
Vue.prototype.$plans = 'plans'
Vue.prototype.$tags = 'tags'
Vue.prototype.$images = 'images'
Vue.prototype.$groups = 'groups'
Vue.prototype.$coaches = 'coaches'
Vue.prototype.$announces = 'announces'
Vue.prototype.$blogs = 'blogs'
Vue.prototype.$subscriptions = 'subscriptions'
Vue.prototype.$clients = 'clients'
Vue.prototype.$links = 'links'
Vue.prototype.$categories = 'categories'

